import type { Fight } from "@/types";

// ── League ─────────────────────────────────────────────────────────────────────

export const mockLeague = {
    id: "la-banda",
    name: "La Banda",
    code: "XK9M2P",
    memberCount: 6,
    scoringSettings: { winner: 10, method: 5, round: 5, decision: 0 },
};

// ── Event ──────────────────────────────────────────────────────────────────────

export const mockEvent = {
    id: "ufc-315",
    name: "UFC 315",
    location: "Montreal, QC",
    date: "2026-05-10",
    mainCardStartAt: "2026-05-11T02:00:00Z",
    prelimsStartAt: "2026-05-10T23:00:00Z",
};

// ── Fights — Main Card ─────────────────────────────────────────────────────────

export const mockMainCard: Fight[] = [
    {
        id: "strickland-vs-hernandez",
        eventId: "ufc-315",
        division: "Middleweight",
        rounds: 5,
        isMainEvent: true,
        isCoMainEvent: false,
        isMainCard: true,
        isPrelim: false,
        status: "SCHEDULED",
        fighterA: {
            id: "sean-strickland",
            name: "Sean Strickland",
            hometown: "Anaheim, California, United States",
            wins: 28,
            losses: 6,
            noContests: 0,
            winsByKo: 11,
            winsBySub: 3,
            winsByDec: 14,
            height: "6'1\"",
            weight: "185 lbs.",
            reach: "76\"",
            imagePath: "https://ufc.com/images/styles/athlete_bio_full_body/s3/2025-01/5/STRICKLAND_SEAN_L_06-01.png?itok=S_BauaBm",
            recentForm: [
                { result: "L", method: "Decision" },
                { result: "W", method: "Decision" },
                { result: "W", method: "Decision" },
            ],
        },
        fighterB: {
            id: "anthony-hernandez",
            name: "Anthony Hernandez",
            hometown: "Los Angeles, California, United States",
            wins: 13,
            losses: 2,
            noContests: 0,
            winsByKo: 5,
            winsBySub: 6,
            winsByDec: 2,
            height: "6'1\"",
            weight: "185 lbs.",
            reach: "75\"",
            imagePath: "https://ufc.com/images/styles/athlete_bio_full_body/s3/2025-01/5/HERNANDEZ_ANTHONY_L_10-19.png?itok=6ys_gZcX",
            recentForm: [
                { result: "W", method: "Submission" },
                { result: "W", method: "KO/TKO" },
                { result: "W", method: "Submission" },
            ],
        },
    },
    {
        id: "blachowicz-vs-ankalaev",
        eventId: "ufc-315",
        division: "Light Heavyweight",
        rounds: 5,
        isMainEvent: false,
        isCoMainEvent: true,
        isMainCard: true,
        isPrelim: false,
        status: "SCHEDULED",
        fighterA: {
            id: "jan-blachowicz",
            name: "Jan Blachowicz",
            hometown: "Cieszyn, Poland",
            wins: 29,
            losses: 10,
            noContests: 0,
            winsByKo: 9,
            winsBySub: 5,
            winsByDec: 15,
            height: "6'2\"",
            weight: "205 lbs.",
            reach: "78\"",
            recentForm: [
                { result: "W", method: "Decision" },
                { result: "L", method: "Decision" },
                { result: "W", method: "KO/TKO" },
            ],
        },
        fighterB: {
            id: "magomed-ankalaev",
            name: "Magomed Ankalaev",
            hometown: "Makhachkala, Republic of Dagestan, Russia",
            wins: 19,
            losses: 1,
            noContests: 1,
            winsByKo: 9,
            winsBySub: 2,
            winsByDec: 8,
            height: "6'3\"",
            weight: "205 lbs.",
            reach: "76\"",
            recentForm: [
                { result: "W", method: "Decision" },
                { result: "W", method: "KO/TKO" },
                { result: "W", method: "Decision" },
            ],
        },
    },
    {
        id: "poirier-vs-fiziev",
        eventId: "ufc-315",
        division: "Lightweight",
        rounds: 3,
        isMainEvent: false,
        isCoMainEvent: false,
        isMainCard: true,
        isPrelim: false,
        status: "SCHEDULED",
        fighterA: {
            id: "dustin-poirier",
            name: "Dustin Poirier",
            hometown: "Lafayette, Louisiana, United States",
            wins: 30,
            losses: 9,
            noContests: 0,
            winsByKo: 15,
            winsBySub: 5,
            winsByDec: 10,
            height: "5'9\"",
            weight: "155 lbs.",
            reach: "72\"",
            recentForm: [
                { result: "L", method: "KO/TKO" },
                { result: "W", method: "KO/TKO" },
                { result: "L", method: "Submission" },
            ],
        },
        fighterB: {
            id: "rafael-fiziev",
            name: "Rafael Fiziev",
            hometown: "Almaty, Kazakhstan",
            wins: 12,
            losses: 3,
            noContests: 0,
            winsByKo: 10,
            winsBySub: 0,
            winsByDec: 2,
            height: "5'10\"",
            weight: "155 lbs.",
            reach: "72\"",
            recentForm: [
                { result: "W", method: "KO/TKO" },
                { result: "L", method: "Decision" },
                { result: "W", method: "KO/TKO" },
            ],
        },
    },
    {
        id: "lemos-vs-andrade",
        eventId: "ufc-315",
        division: "Women's Strawweight",
        rounds: 3,
        isMainEvent: false,
        isCoMainEvent: false,
        isMainCard: true,
        isPrelim: false,
        status: "SCHEDULED",
        fighterA: {
            id: "amanda-lemos",
            name: "Amanda Lemos",
            hometown: "Belem, Para, Brazil",
            wins: 13,
            losses: 3,
            noContests: 1,
            winsByKo: 6,
            winsBySub: 4,
            winsByDec: 3,
            height: "5'4\"",
            weight: "115 lbs.",
            reach: "66\"",
            recentForm: [
                { result: "W", method: "Decision" },
                { result: "W", method: "KO/TKO" },
                { result: "W", method: "Submission" },
            ],
        },
        fighterB: {
            id: "jessica-andrade",
            name: "Jessica Andrade",
            hometown: "Umuarama, Parana, Brazil",
            wins: 24,
            losses: 12,
            noContests: 0,
            winsByKo: 12,
            winsBySub: 4,
            winsByDec: 8,
            height: "5'1\"",
            weight: "115 lbs.",
            reach: "59\"",
            recentForm: [
                { result: "L", method: "Decision" },
                { result: "W", method: "KO/TKO" },
                { result: "L", method: "Decision" },
            ],
        },
    },
    {
        id: "rountree-vs-walker",
        eventId: "ufc-315",
        division: "Light Heavyweight",
        rounds: 3,
        isMainEvent: false,
        isCoMainEvent: false,
        isMainCard: true,
        isPrelim: false,
        status: "SCHEDULED",
        fighterA: {
            id: "khalil-rountree",
            name: "Khalil Rountree",
            hometown: "Las Vegas, Nevada, United States",
            wins: 12,
            losses: 5,
            noContests: 2,
            winsByKo: 11,
            winsBySub: 0,
            winsByDec: 1,
            height: "6'1\"",
            weight: "205 lbs.",
            reach: "77\"",
            recentForm: [
                { result: "W", method: "KO/TKO" },
                { result: "W", method: "KO/TKO" },
                { result: "W", method: "KO/TKO" },
            ],
        },
        fighterB: {
            id: "johnny-walker",
            name: "Johnny Walker",
            hometown: "Fortaleza, Ceara, Brazil",
            wins: 22,
            losses: 8,
            noContests: 0,
            winsByKo: 18,
            winsBySub: 2,
            winsByDec: 2,
            height: "6'5\"",
            weight: "205 lbs.",
            reach: "80\"",
            recentForm: [
                { result: "L", method: "Decision" },
                { result: "W", method: "KO/TKO" },
                { result: "W", method: "KO/TKO" },
            ],
        },
    },
];

// ── Fights — Prelims ───────────────────────────────────────────────────────────

export const mockPrelims: Fight[] = [
    {
        id: "barriault-vs-anders",
        eventId: "ufc-315",
        division: "Middleweight",
        rounds: 3,
        isMainEvent: false,
        isCoMainEvent: false,
        isMainCard: false,
        isPrelim: true,
        status: "SCHEDULED",
        fighterA: {
            id: "marc-andre-barriault",
            name: "Marc-André Barriault",
            hometown: "Saint-Jean-sur-Richelieu, Quebec, Canada",
            wins: 17,
            losses: 6,
            noContests: 1,
            winsByKo: 10,
            winsBySub: 2,
            winsByDec: 5,
            height: "6'2\"",
            weight: "185 lbs.",
            reach: "77\"",
            recentForm: [
                { result: "W", method: "KO/TKO" },
                { result: "L", method: "Decision" },
                { result: "W", method: "Decision" },
            ],
        },
        fighterB: {
            id: "eryk-anders",
            name: "Eryk Anders",
            hometown: "Birmingham, Alabama, United States",
            wins: 14,
            losses: 8,
            noContests: 0,
            winsByKo: 6,
            winsBySub: 4,
            winsByDec: 4,
            height: "6'2\"",
            weight: "185 lbs.",
            reach: "77.5\"",
            recentForm: [
                { result: "L", method: "Decision" },
                { result: "L", method: "KO/TKO" },
                { result: "W", method: "Decision" },
            ],
        },
    },
    {
        id: "ricci-vs-belbita",
        eventId: "ufc-315",
        division: "Women's Strawweight",
        rounds: 3,
        isMainEvent: false,
        isCoMainEvent: false,
        isMainCard: false,
        isPrelim: true,
        status: "SCHEDULED",
        fighterA: {
            id: "tabitha-ricci",
            name: "Tabitha Ricci",
            hometown: "Burlington, Ontario, Canada",
            wins: 10,
            losses: 3,
            noContests: 0,
            winsByKo: 1,
            winsBySub: 3,
            winsByDec: 6,
            height: "5'7\"",
            weight: "115 lbs.",
            reach: "68\"",
            recentForm: [
                { result: "L", method: "Decision" },
                { result: "W", method: "Decision" },
                { result: "W", method: "Decision" },
            ],
        },
        fighterB: {
            id: "diana-belbita",
            name: "Diana Belbita",
            hometown: "Timisoara, Timis, Romania",
            wins: 19,
            losses: 8,
            noContests: 0,
            winsByKo: 4,
            winsBySub: 5,
            winsByDec: 10,
            height: "5'8\"",
            weight: "115 lbs.",
            reach: "67\"",
            recentForm: [
                { result: "W", method: "Decision" },
                { result: "L", method: "KO/TKO" },
                { result: "W", method: "Decision" },
            ],
        },
    },
    {
        id: "haqparast-vs-azaitar",
        eventId: "ufc-315",
        division: "Lightweight",
        rounds: 3,
        isMainEvent: false,
        isCoMainEvent: false,
        isMainCard: false,
        isPrelim: true,
        status: "SCHEDULED",
        fighterA: {
            id: "nasrat-haqparast",
            name: "Nasrat Haqparast",
            hometown: "Kaiserslautern, Germany",
            wins: 15,
            losses: 5,
            noContests: 0,
            winsByKo: 7,
            winsBySub: 2,
            winsByDec: 6,
            height: "5'10\"",
            weight: "155 lbs.",
            reach: "72\"",
            recentForm: [
                { result: "W", method: "Decision" },
                { result: "W", method: "KO/TKO" },
                { result: "L", method: "Decision" },
            ],
        },
        fighterB: {
            id: "ottman-azaitar",
            name: "Ottman Azaitar",
            hometown: "Basel, Switzerland",
            wins: 13,
            losses: 2,
            noContests: 0,
            winsByKo: 12,
            winsBySub: 1,
            winsByDec: 0,
            height: "5'10\"",
            weight: "155 lbs.",
            reach: "73\"",
            recentForm: [
                { result: "W", method: "KO/TKO" },
                { result: "W", method: "KO/TKO" },
                { result: "W", method: "KO/TKO" },
            ],
        },
    },
    {
        id: "robertson-vs-rodriguez",
        eventId: "ufc-315",
        division: "Women's Flyweight",
        rounds: 3,
        isMainEvent: false,
        isCoMainEvent: false,
        isMainCard: false,
        isPrelim: true,
        status: "SCHEDULED",
        fighterA: {
            id: "gillian-robertson",
            name: "Gillian Robertson",
            hometown: "Georgetown, Ontario, Canada",
            wins: 12,
            losses: 6,
            noContests: 0,
            winsByKo: 0,
            winsBySub: 10,
            winsByDec: 2,
            height: "5'4\"",
            weight: "125 lbs.",
            reach: "64\"",
            recentForm: [
                { result: "W", method: "Submission" },
                { result: "W", method: "Submission" },
                { result: "L", method: "Decision" },
            ],
        },
        fighterB: {
            id: "piera-rodriguez",
            name: "Piera Rodriguez",
            hometown: "Caracas, Venezuela",
            wins: 11,
            losses: 2,
            noContests: 0,
            winsByKo: 3,
            winsBySub: 3,
            winsByDec: 5,
            height: "5'5\"",
            weight: "125 lbs.",
            reach: "65\"",
            recentForm: [
                { result: "W", method: "Decision" },
                { result: "W", method: "KO/TKO" },
                { result: "W", method: "Decision" },
            ],
        },
    },
];

// ── Leagues list (for Explore) ────────────────────────────────────────────────

export const mockLeagues = [
    { id: "la-banda",     name: "La Banda",          code: "XK9M2P", memberCount: 6, isOwner: true,  survivorEnabled: false, currentEvent: "UFC 315" },
    { id: "les-experts",  name: "Les Experts UFC",   code: "MZ5T9R", memberCount: 4, isOwner: false, survivorEnabled: true,  currentEvent: "UFC 315" },
];

// ── Standings ──────────────────────────────────────────────────────────────────

export const mockStandings = [
    { rank: 1, username: "maxbfr",    points: 65, correct: 6, total: 8, perfectPicks: 2, betsPlaced: 8, isCurrentUser: false },
    { rank: 2, username: "mika_oct",  points: 55, correct: 5, total: 8, perfectPicks: 2, betsPlaced: 8, isCurrentUser: false },
    { rank: 3, username: "toto_mma",  points: 50, correct: 5, total: 8, perfectPicks: 1, betsPlaced: 8, isCurrentUser: false },
    { rank: 4, username: "vous",      points: 45, correct: 4, total: 8, perfectPicks: 1, betsPlaced: 8, isCurrentUser: true  },
    { rank: 5, username: "jv_mma",    points: 30, correct: 3, total: 8, perfectPicks: 0, betsPlaced: 8, isCurrentUser: false },
    { rank: 6, username: "claireUFC", points: 20, correct: 2, total: 8, perfectPicks: 0, betsPlaced: 7, isCurrentUser: false },
];
