### Get league bets

GET http://localhost:3000/api/v1/leagues/8803cc0e-5dda-48bc-8c1f-afde20ee98d4/bets
Accept: application/json, text/plain, */*
Accept-Language: fr-CA,fr;q=0.9,en-US;q=0.8,en;q=0.7
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImEwZjI1YzU3LTkzYzYtNDY4NS1hYzljLTMwNDI5MWJmNzViZCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2tlbXJucnl6anJyb2tzbGhudnVsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlYTY4M2NjZS1mZTBmLTRjOTYtODE4NC04ZWQ3ZGM0NWM2MzYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzcxNTIzNTkxLCJpYXQiOjE3NzE1MTk5OTEsImVtYWlsIjoibWF0dGhpZXUuZ2F1dGhpZXJAbWUuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzE1MTYyOTN9XSwic2Vzc2lvbl9pZCI6IjBkMDQ3ZjE2LTU1MmYtNDFmZS04MGIwLThkZWRhMjQ0YmZiNSIsImlzX2Fub255bW91cyI6ZmFsc2V9.jPa3MicJumPi4y1KGp0h9SCpZhpMrrJ-2yh61X6rECgTskyT-b4YNjW8cAG6tW516fr5IVeENxRTD3_NTA25sQ
Connection: keep-alive
Origin: http://localhost:5173
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
